### ISSUE TITLE
ci workflow run failed in Windows (My compiler and everything is in WSL)

### ISSUE THREAD

**Issue by MarcusMors** [cpp-best-practices/cmake_template#14]
[repository](https://github.com/MarcusMors/Snake/actions)

I followed the video instructions and the README_troubleshooting.md steps (the last 2 weren't very helpful since I have never used conan before, I just installed it on my own). The problem persists.

OS: Windows ("naked" environment, no compiler, not a lot of programs or tools here)
¿sub OS?: WSL (here is where I have everything I use)
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

problematic jobs:

- all test ubuntu 20.04 gcc-11
- all test macos-10.15 gcc-11
- test ubuntu 20.04 gcc-11 Unix makefiles, Debug On
- Test windows-2022, msvc Visual Studio 17 2022, Debug On
- Test windows-2022, msvc Visual Studio 17 2022, Release On

previously i have installed conan, this is its path: `/usr/local/bin/conan`

these are the versions of compilers i have in WSL
g++ (Ubuntu 9.3.0-17ubuntu1\~20.04) 9.3.0
g++-10 (Ubuntu 10.3.0-1ubuntu1\~20.04) 10.3.0
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by lefticus** [comment]
The version of g++ is too old to support the project, and I just made it worse by using more C++20 features, so I'm going to have to close this.
