### ISSUE TITLE
Template Janitor does not replace all instances of "myproject" with new project name

### ISSUE THREAD

**Issue by benmccart** [cpp-best-practices/cmake_template#39]
After using the template janitor on a dry run (private project) I ended up with "include/myproject" instead of "include/privateproject"

In my case I was expecting the name "privateproject" to get used here.

**Comment by St0wy** [comment]
Was template janitor able to push to your project ? I think I have the same issue because when the template janitor pushes, I get this error : 

```
Error: Error: Pushing to https://github.com/St0wy/fun-with-images
remote: Permission to St0wy/fun-with-images.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/St0wy/fun-with-images/': The requested URL returned error: 403
```
